const hiraganaData = [
    {"character": "あ", "pronunciation": "a","level":1},
    { "character": "い", "pronunciation": "i","level": 1 },
    { "character": "う", "pronunciation": "u", "level": 1 },
    { "character": "え", "pronunciation": "e", "level": 1 },
    { "character": "お", "pronunciation": "o", "level": 1 },
    { "character": "か", "pronunciation": "ka", "level": 0 },
    { "character": "き", "pronunciation": "ki", "level": 0 },
    { "character": "く", "pronunciation": "ku", "level": 0 },
    { "character": "け", "pronunciation": "ke", "level": 0 },
    { "character": "こ", "pronunciation": "ko", "level": 0 },
    { "character": "さ", "pronunciation": "sa", "level": 0 },
    { "character": "し", "pronunciation": "shi", "level": 0 },
    { "character": "す", "pronunciation": "su", "level": 0 },
    { "character": "せ", "pronunciation": "se", "level": 0 },
    { "character": "そ", "pronunciation": "so", "level": 0 },
    { "character": "た", "pronunciation": "ta", "level": 0 },
    { "character": "ち", "pronunciation": "chi", "level": 0 },
    { "character": "つ", "pronunciation": "tsu", "level": 0 },
    { "character": "て", "pronunciation": "te", "level": 0 },
    { "character": "と", "pronunciation": "to", "level": 0 },
    { "character": "な", "pronunciation": "na", "level": 0 },
    { "character": "に", "pronunciation": "ni", "level": 0 },
    { "character": "ぬ", "pronunciation": "nu", "level": 0 },
    { "character": "ね", "pronunciation": "ne", "level": 0 },
    { "character": "の", "pronunciation": "no", "level": 0 },
    { "character": "は", "pronunciation": "ha", "level": 0 },
    { "character": "ひ", "pronunciation": "hi", "level": 0 },
    { "character": "ふ", "pronunciation": "fu", "level": 0 },
    { "character": "へ", "pronunciation": "he", "level": 0 },
    { "character": "ほ", "pronunciation": "ho", "level": 0 },
    { "character": "ま", "pronunciation": "ma", "level": 0 },
    { "character": "み", "pronunciation": "mi", "level": 0 },
    { "character": "む", "pronunciation": "mu", "level": 0 },
    { "character": "め", "pronunciation": "me", "level": 0 },
    { "character": "も", "pronunciation": "mo", "level": 0 },
    { "character": "や", "pronunciation": "ya", "level": 0 },
    { "character": "ゆ", "pronunciation": "yu", "level": 0 },
    { "character": "よ", "pronunciation": "yo", "level": 0 },
    { "character": "ら", "pronunciation": "ra", "level": 0 },
    { "character": "り", "pronunciation": "ri", "level": 0 },
    { "character": "る", "pronunciation": "ru", "level": 0 },
    { "character": "れ", "pronunciation": "re", "level": 0 },
    { "character": "ろ", "pronunciation": "ro", "level": 0 },
    { "character": "わ", "pronunciation": "wa", "level": 0 },
    { "character": "を", "pronunciation": "wo", "level": 0 },
    { "character": "ん", "pronunciation": "n", "level": 0 }
  ]

export default hiraganaData;